# Generated by Django 3.2.17 on 2023-04-03 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='как будет называться команда?',
                        max_length=150,
                        unique=True,
                        verbose_name='название команды',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='когда создана команда?',
                        verbose_name='дата создания',
                    ),
                ),
                (
                    'is_open',
                    models.BooleanField(
                        default=True,
                        help_text='показывается ли ваша команда в поиске?',
                        verbose_name='открытость',
                    ),
                ),
                (
                    'tasks',
                    models.ForeignKey(
                        help_text='задания для команды',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='team',
                        to='tasks.task',
                        verbose_name='задания',
                    ),
                ),
            ],
            options={
                'verbose_name': 'команда',
                'verbose_name_plural': 'команды',
                'default_related_name': 'team',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'to_team',
                    models.ForeignKey(
                        help_text='в какую команду приглашение?',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invite',
                        to='teams.team',
                        verbose_name='команда',
                    ),
                ),
            ],
            options={
                'verbose_name': 'приглашение',
                'verbose_name_plural': 'приглашения',
                'default_related_name': 'invite',
            },
        ),
    ]
