# Generated by Django 3.2.17 on 2023-04-17 11:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0001_squashed_0003_alter_team_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='meetings',
        ),
        migrations.RemoveField(
            model_name='team',
            name='tasks',
        ),
    ]
