# Generated by Django 3.2.17 on 2023-04-06 18:10

from django.db import migrations, models
import django.db.models.deletion
import teams.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20230406_2110'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='avatar',
            field=models.ImageField(blank=True, help_text='картинка профиля команды', null=True, upload_to=teams.models.avatar_image_path, verbose_name='аватарка'),
        ),
        migrations.AddField(
            model_name='team',
            name='detail',
            field=models.TextField(help_text='более подробное описание', null=True, verbose_name='детали'),
        ),
        migrations.AddField(
            model_name='team',
            name='meetings',
            field=models.ForeignKey(default='', help_text='запланированные командные встречи', on_delete=django.db.models.deletion.CASCADE, related_name='team', to='tasks.meeting', verbose_name='встречи'),
        ),
        migrations.AddField(
            model_name='team',
            name='unique_name',
            field=models.CharField(editable=False, help_text='Колонка для проверки уникальности названия', max_length=150, null=True, unique=True, verbose_name='уникальное имя'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='как называется?', max_length=150, verbose_name='название'),
        ),
    ]
