# Generated by Django 3.2.17 on 2023-04-15 09:57

from django.db import migrations, models

import teams.models


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0002_alter_team_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(
                blank=True,
                default='/static/img/team_default.png',
                help_text='картинка профиля команды',
                upload_to=teams.models.avatar_image_path,
                verbose_name='аватарка',
            ),
        ),
    ]
