# Generated by Django 3.2.17 on 2023-04-07 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0003_auto_20230407_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='to_team',
        ),
    ]
