# Generated by Django 3.2.17 on 2023-04-07 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20230407_1706'),
        ('teams', '0004_remove_invite_to_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
