# Generated by Django 3.2.17 on 2023-04-06 19:36

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import users.managers
import users.models


class Migration(migrations.Migration):
    replaces = [
        ('users', '0001_squashed_0002_auto_20230404_2017'),
        ('users', '0002_alter_user_invites'),
        ('users', '0003_auto_20230406_1921'),
        ('users', '0004_alter_user_managers'),
        ('users', '0005_user_skills'),
        ('users', '0006_alter_user_skills'),
    ]

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('skills', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'password',
                    models.CharField(max_length=128, verbose_name='password'),
                ),
                (
                    'last_login',
                    models.DateTimeField(
                        blank=True, null=True, verbose_name='last login'
                    ),
                ),
                (
                    'is_superuser',
                    models.BooleanField(
                        default=False,
                        help_text='Designates that this user has all permissions without explicitly assigning them.',
                        verbose_name='superuser status',
                    ),
                ),
                (
                    'username',
                    models.CharField(
                        error_messages={
                            'unique': 'A user with that username already exists.'
                        },
                        help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.',
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name='username',
                    ),
                ),
                (
                    'first_name',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='first name'
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        blank=True, max_length=150, verbose_name='last name'
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        verbose_name='email address',
                    ),
                ),
                (
                    'is_staff',
                    models.BooleanField(
                        default=False,
                        help_text='Designates whether the user can log into this admin site.',
                        verbose_name='staff status',
                    ),
                ),
                (
                    'is_active',
                    models.BooleanField(
                        default=True,
                        help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.',
                        verbose_name='active',
                    ),
                ),
                (
                    'date_joined',
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name='date joined',
                    ),
                ),
                (
                    'is_visible',
                    models.BooleanField(
                        default=True,
                        help_text='могут ли другие пользователи звать вас в команды?',
                        verbose_name='статус видимости',
                    ),
                ),
                (
                    'groups',
                    models.ManyToManyField(
                        blank=True,
                        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.Group',
                        verbose_name='groups',
                    ),
                ),
                (
                    'invites',
                    models.ForeignKey(
                        help_text='куда вас пригласили?',
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='user',
                        to='teams.invite',
                        verbose_name='приглашения',
                    ),
                ),
                (
                    'members',
                    models.ManyToManyField(
                        help_text='в каких команда вы состоите?',
                        related_name='members',
                        to='teams.Team',
                        verbose_name='команды',
                    ),
                ),
                (
                    'user_permissions',
                    models.ManyToManyField(
                        blank=True,
                        help_text='Specific permissions for this user.',
                        related_name='user_set',
                        related_query_name='user',
                        to='auth.Permission',
                        verbose_name='user permissions',
                    ),
                ),
                (
                    'avatar',
                    models.ImageField(
                        blank=True,
                        help_text='картинка профиля пользователя',
                        null=True,
                        upload_to=users.models.avatar_image_path,
                        verbose_name='аватарка',
                    ),
                ),
                (
                    'failed_logins',
                    models.IntegerField(
                        default=0,
                        help_text='сколько раз был провален вход в аккаунт',
                        verbose_name='количество неудачных входов с момента удачного',
                    ),
                ),
                (
                    'last_failed_login_date',
                    models.DateTimeField(
                        null=True,
                        verbose_name='дата последней неудачной попытки входа',
                    ),
                ),
                (
                    'lead_teams',
                    models.ManyToManyField(
                        help_text='какими командами вы управляете?',
                        related_name='leads',
                        to='teams.Team',
                        verbose_name='управляемые команды',
                    ),
                ),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'default_related_name': 'user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.ActiveUserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(
                help_text='Ваши навыки',
                related_name='user',
                to='skills.Skill',
                verbose_name='навыки',
            ),
        ),
    ]
