# Generated by Django 3.2.17 on 2023-04-05 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0001_initial'),
        ('users', '0001_squashed_0002_auto_20230404_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invites',
            field=models.ForeignKey(
                help_text='куда вас пригласили?',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user',
                to='teams.invite',
                verbose_name='приглашения',
            ),
        ),
    ]
