# Generated by Django 3.2.17 on 2023-04-07 14:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0004_remove_invite_to_team'),
        ('users', '0001_squashed_0006_alter_user_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='invites',
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'to_team',
                    models.ForeignKey(
                        help_text='в какую команду приглашение?',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='invite',
                        to='teams.team',
                        verbose_name='команда',
                    ),
                ),
                (
                    'to_user',
                    models.ForeignKey(
                        help_text='какому пользователю приглашение?',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='invite',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'приглашение',
                'verbose_name_plural': 'приглашения',
                'default_related_name': 'invite',
            },
        ),
    ]
