# Generated by Django 3.2.17 on 2023-04-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('skills', '0001_initial'),
        ('tasks', '0001_squashed_0002_alter_meeting_status'),
        ('teams', '0001_squashed_0005_delete_invite'),
        ('users', '0001_squashed_0006_user_tasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lead_teams',
            field=models.ManyToManyField(
                blank=True,
                help_text='какими командами вы управляете?',
                related_name='leads',
                to='teams.Team',
                verbose_name='управляемые команды',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(
                blank=True,
                help_text='Ваши навыки',
                related_name='user',
                to='skills.Skill',
                verbose_name='навыки',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(
                blank=True,
                help_text='задачи, назначенные вам',
                related_name='to_users',
                to='tasks.Task',
                verbose_name='задачи',
            ),
        ),
        migrations.AlterField(
            model_name='user',
            name='teams',
            field=models.ManyToManyField(
                blank=True,
                help_text='в каких команда вы состоите?',
                related_name='members',
                to='teams.Team',
                verbose_name='команды',
            ),
        ),
    ]
