# Generated by Django 3.2.17 on 2023-04-15 09:56

from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20230410_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True,
                default='/static/img/default.jpg',
                help_text='картинка профиля пользователя',
                null=True,
                upload_to=users.models.avatar_image_path,
                verbose_name='аватарка',
            ),
        ),
    ]
