# Generated by Django 3.2.17 on 2023-04-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0001_initial'),
        ('users', '0002_alter_user_invites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='lead',
        ),
        migrations.AddField(
            model_name='user',
            name='lead_teams',
            field=models.ManyToManyField(
                help_text='какими командами вы управляете?',
                related_name='leads',
                to='teams.Team',
                verbose_name='управляемые команды',
            ),
        ),
    ]
