# Generated by Django 3.2.17 on 2023-04-07 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0002_auto_20230407_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='members',
            new_name='teams',
        ),
    ]
