# Generated by Django 3.2.17 on 2023-04-17 06:57

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tasks',
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(
                blank=True,
                help_text='картинка профиля пользователя',
                null=True,
                upload_to=users.models.avatar_image_path,
                verbose_name='аватарка',
            ),
        ),
    ]
