# Generated by Django 3.2.17 on 2023-04-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0003_rename_members_user_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='detail',
            field=models.TextField(
                help_text='расскажите о себе детальнее',
                max_length=550,
                null=True,
                verbose_name='детали',
            ),
        ),
    ]
