# Generated by Django 3.2.17 on 2023-04-07 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('teams', '0005_delete_invite'),
        ('users', '0004_user_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invite',
            old_name='to_team',
            new_name='from_team',
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'from_user',
                    models.ForeignKey(
                        help_text='кто отправил запрос?',
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name='request',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='пользователь',
                    ),
                ),
                (
                    'to_team',
                    models.ForeignKey(
                        help_text='в какому команду подан запрос?',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='request',
                        to='teams.team',
                        verbose_name='команда',
                    ),
                ),
            ],
            options={
                'verbose_name': 'запрос на вступление',
                'verbose_name_plural': 'запросы на вступление',
                'default_related_name': 'request',
            },
        ),
    ]
