# Generated by Django 3.2.17 on 2023-04-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0002_alter_meeting_status'),
        ('users', '0005_auto_20230407_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tasks',
            field=models.ManyToManyField(
                help_text='задачи, назначенные вам',
                related_name='to_users',
                to='tasks.Task',
                verbose_name='задачи',
            ),
        ),
    ]
