# Generated by Django 3.2.17 on 2023-04-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='как будет называться задача?',
                        max_length=150,
                        unique=True,
                        verbose_name='название задачи',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='когда создана команда?',
                        verbose_name='дата создания',
                    ),
                ),
                (
                    'deadline_date',
                    models.DateTimeField(
                        help_text='до какого времени надо сдать задачу?',
                        verbose_name='дата дедлайна',
                    ),
                ),
                (
                    'completed_date',
                    models.DateTimeField(
                        help_text='когда была выполнена задача?',
                        null=True,
                        verbose_name='дата выполнения',
                    ),
                ),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'default_related_name': 'task',
            },
        ),
    ]
