# Generated by Django 3.2.17 on 2023-04-18 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ('tasks', '0001_squashed_0002_auto_20230416_1505'),
        ('tasks', '0002_auto_20230418_0916'),
        ('tasks', '0003_auto_20230418_0916'),
    ]

    dependencies = [
        ('teams', '0001_squashed_0002_auto_20230418_0916'),
    ]

    initial = True

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='как называется?',
                        max_length=150,
                        verbose_name='название',
                    ),
                ),
                (
                    'detail',
                    models.TextField(
                        blank=True,
                        help_text='более подробное описание',
                        null=True,
                        verbose_name='детали',
                    ),
                ),
                (
                    'planned_date',
                    models.DateTimeField(
                        help_text='когда пройдёт митап?',
                        verbose_name='дата встречи',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='meetings',
                        to='teams.team',
                        verbose_name='команда',
                    ),
                ),
            ],
            options={
                'verbose_name': 'встреча',
                'verbose_name_plural': 'встречи',
                'default_related_name': 'meeting',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(
                        help_text='как называется?',
                        max_length=150,
                        verbose_name='название',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='когда создана команда?',
                        verbose_name='дата создания',
                    ),
                ),
                (
                    'deadline_date',
                    models.DateTimeField(
                        help_text='до какого времени надо сдать задачу?',
                        verbose_name='дата дедлайна',
                    ),
                ),
                (
                    'completed_date',
                    models.DateTimeField(
                        help_text='когда была выполнена задача?',
                        verbose_name='дата выполнения',
                    ),
                ),
                (
                    'detail',
                    models.TextField(
                        blank=True,
                        help_text='более подробное описание',
                        null=True,
                        verbose_name='детали',
                    ),
                ),
                (
                    'team',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='tasks',
                        to='teams.team',
                        verbose_name='команда',
                    ),
                ),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'default_related_name': 'task',
            },
        ),
    ]
