# Generated by Django 3.2.17 on 2023-04-17 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0001_squashed_0002_alter_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(
                blank=True,
                related_name='tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователи',
            ),
        ),
    ]
