# Generated by Django 3.2.17 on 2023-04-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='как называется?', max_length=150, verbose_name='название')),
                ('detail', models.TextField(help_text='более подробное описание', null=True, verbose_name='детали')),
                ('planned_date', models.DateTimeField(help_text='когда пройдёт митап?', verbose_name='дата встречи')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ожидается'), (2, 'Идёт'), (3, 'Закончилась')], help_text='текущий статус встречи', verbose_name='статус')),
            ],
            options={
                'verbose_name': 'встреча',
                'verbose_name_plural': 'встречи',
                'default_related_name': 'meeting',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='detail',
            field=models.TextField(help_text='более подробное описание', null=True, verbose_name='детали'),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(help_text='как называется?', max_length=150, verbose_name='название'),
        ),
    ]
