# Generated by Django 3.2.17 on 2023-04-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0001_squashed_0002_auto_20230406_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.PositiveSmallIntegerField(
                choices=[(0, 'Ожидается'), (1, 'Идёт'), (2, 'Закончилась')],
                default=0,
                help_text='текущий статус встречи',
                verbose_name='статус',
            ),
        ),
    ]
