# Generated by Django 3.2.17 on 2023-04-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='когда создано задание?', verbose_name='дата создания'),
        ),
    ]
