# Generated by Django 3.2.17 on 2023-04-19 18:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0003_task_is_completed_squashed_0004_auto_20230419_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
    ]
