# Generated by Django 3.2.17 on 2023-04-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('tasks', '0004_remove_task_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(
                help_text='как называется?',
                max_length=20,
                null=True,
                verbose_name='название',
            ),
        ),
    ]
