# Generated by Django 3.2.17 on 2023-04-18 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ('tasks', '0002_auto_20230418_1935'),
        ('tasks', '0003_alter_task_deadline_date'),
    ]

    dependencies = [
        ('tasks', '0001_squashed_0002_alter_meeting_team'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='users',
            field=models.ManyToManyField(
                blank=True,
                related_name='tasks',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователи',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(
                help_text='когда была выполнена задача?',
                null=True,
                verbose_name='дата выполнения',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='когда создано задание?',
                verbose_name='дата создания',
            ),
        ),
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateTimeField(
                help_text='до какого времени надо сдать задачу?',
                verbose_name='дата дедлайна (формат: год-месяц-день)',
            ),
        ),
    ]
