# Generated by Django 3.2.17 on 2023-04-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ('tasks', '0004_remove_task_is_completed'),
        ('tasks', '0005_alter_meeting_name'),
        ('tasks', '0006_alter_meeting_name'),
    ]

    dependencies = [
        ('tasks', '0003_task_is_completed_squashed_0004_auto_20230419_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_completed',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(
                help_text='как называется?',
                max_length=20,
                null=True,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='name',
            field=models.CharField(
                help_text='как называется?',
                max_length=20,
                verbose_name='название',
            ),
        ),
    ]
