name: Python linting

on:
  push:
    branches: [ "main", "develop", "feature/Egor" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r project/requirements/test-requirements.txt
        pip install -r project/requirements/dev-requirements.txt
    - name: Lint with flake8
      run: |
        cd project/
        flake8 . --count --show-source --statistics
        black --skip-string-normalization --verbose --check --diff .
